base_url = "https://syedzayyan.github.io/"
title = "Syed Zayyan Masud"
generate_feed = true
compile_sass = true
minify_html = true

taxonomies = [
    {name = "tags", feed = true},
]

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"

[extra]
toc = true
use_cdn = false
favicon = "/menu_icon/profile_pic.png"

menu = [
    { name = "Projects", url = "/projects", weight = 1, icon = "projects" },
    { name = "About", url = "/about", weight = 2, icon = "profile_pic" },
]

socials = [
    { name = "youtube", url = "https://youtube.com/@zayyanmasud", icon = "youtube" },
    { name = "github", url = "https://github.com/not-matthias/", icon = "github" },
]